- hosts: all
  tasks: 
    - name: 5 users are added with ssh keys on new instance
      user: 
        name: "{{ item }}"
        comment: DevOps
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      with_items:
        - bob
        - lisa
        - ben
        - ken
        - tim


  #   my_ssh_users:
  # - name: bob
  #   key: "{{ lookup('file', 'bob.pub') }}"
  # - name: lisa
  #   key: "{{ lookup('file', 'lisa.pub') }}"
  # - name: ben
  #   key: "{{ lookup('file', 'ben.pub') }}"
  # - name: ken
  #   key: "{{ lookup('file', 'ken.pub') }}"
  # - name: tim
  #   key: "{{ lookup('file', 'tim.pub') }}"
# ...
# - name: Add ssh pub keys
#   authorized_key: user={{ item.name }} key="{{ item.key }}"
#   with_items: my_ssh_users

# - name: Copy the key add to authorized_keys using Ansible module
#       tags: runcd
#       authorized_key:
#         user: vagrant
#         state: present
#         key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
#       when: "{{ item != ansible_hostname }}"
#       with_items: 
#         - "{{ groups['multi'] }}" 
   


    # # - name: Copy file with owner and permissions
    #   shell: sudo scp -rf {{ansible_host}}"/home/centos/.ssh/authorized_keys  centos@35.174.7.164:/home/centos/.ssh





  